enemy_color: "red"
# enemy_color: "blue"

# 机器人类型配置（hero或其他）
robot_type: "hero"  # hero为英雄机器人，其他为普通机器人
tradition_detect: false
#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: GPU
min_confidence: 0.7 #0.8 #原检测阈值
use_traditional: false

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
# min_confidence: 0.8

#####-----tracker参数-----#####
min_detect_count: 5               #追踪检测次数阈值
max_temp_lost_count: 15           #装甲板最大丢失帧数
outpost_max_temp_lost_count: 75   #前哨站最大丢失帧数

#####-----aimer参数-----#####
yaw_offset: 0 # degree -2.5
pitch_offset: 0 # degree 2
comming_angle: 60 # degree
leaving_angle: 20 # degree
decision_speed: 10 # rad/s
high_speed_delay_time: 0.026 # s
low_speed_delay_time: 0.010 # s
# high_speed_delay_time: 1.0 # s
# low_speed_delay_time: 1.0 # s

#####-----shooter参数-----#####
first_tolerance: 2 # 近距离射击容差，degree
second_tolerance: 1 # 远距离射击容差，degree
judge_distance: 3 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击
 
camera_name: "hikrobot"
exposure_ms: 4
gain: 16
vid_pid: "2bdf:0001"

#  1  0  0
#  0  1  0
#  0  0  1

R_gimbal2imubody: [0, -1, 0,
                  1, 0, 0,
                  0, 0, 1]
# R_gimbal2imubody: [1, 0, 0,
#                   0, -1, 0,
#                   0, 0, -1]

# 重投影误差: 0.2107px
camera_matrix: [2292.0275817422962, 0, 730.9833139759603, 0, 2292.8812845258312, 586.12025110046659, 0, 0, 1]
distort_coeffs: [-0.060928956724159829, 0.24158248704129962, 0.003218516634930931, 0.0013140084182289827, 0]





# 相机同理想情况的偏角: yaw-2.01 pitch-0.95 roll-0.47 degree
# R_camera2gimbal: [0.0352684454494403, -0.01627514092472182, 0.99924534351852756, -0.99934400433065129, -0.0088062320068609257, 0.035128496782814989, 0.0082278650911856155, -0.99982877037306817, -0.016575046615906253]
# t_camera2gimbal: [0.22866352994732525, -0.013384231496827057, 0.042695860756217986]


# # 相机同理想情况的偏角: yaw-1.05 pitch-0.95 roll-0.13 degree
R_camera2gimbal: [0, 0, 1, -1, 0, 0, 0, -1, 0]
t_camera2gimbal: [0.11, 0, 0.084]



# t_camera2gimbal: [0.078, 0, 0.081]


# #####-----cboard参数-----#####
# quaternion_canid: 0x100
# bullet_speed_canid: 0x101
# send_canid: 0xff
# can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/ttyUSB0"
speed_control: false
bullet_speed: 12  # m/s

# #####-----planner-----#####
# fire_thresh: 0.003

# max_yaw_acc: 50
# Q_yaw: [9e6, 0]
# R_yaw: [1]

# max_pitch_acc: 100
# Q_pitch: [9e6,0]
# R_pitch: [1]

# #####-----buff_detector参数-----#####
# model: "assets/yolo11_buff_int8.xml"

# #####-----buff_aimer参数-----#####
# fire_gap_time: 0.520   # s
# predict_time: 0.100     # s